<?php
/* Write a SQL query to retrieve all the customer information along with the total number of orders placed by each customer. Display the result in descending order of the number of orders.
 */
SELECT `customers`.`customer_id`, `customers`.`name`, `customers`.`email`, `customers`.`location`, COUNT(`orders`.`order_id`) AS `total_orders`
FROM `customers`
LEFT JOIN `orders` ON `customers`.`customer_id` = `orders`.`customer_id`
GROUP BY `customers`.`customer_id`
ORDER BY `total_orders` DESC;

/* --Write a SQL query to retrieve the product name, quantity, and total amount for each order item. Display the result in ascending order of the order ID. */
SELECT `order_items`.`order_id`, `products`.`name`, `order_items`.`quantity`, `order_items`.`unit_price`, `order_items`.`quantity` * `order_items`.`unit_price` AS `total_amount`
FROM `order_items`
JOIN `products` ON `order_items`.`product_id` = `products`.`product_id`
ORDER BY `order_id`;
/* --Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue. */
SELECT `categories`.`name`, SUM(`order_items`.`quantity` * `order_items`.`unit_price`) AS `total_revenue`
FROM `categories`
JOIN `products` ON `categories`.`category_id` = `products`.`category_id`
JOIN `order_items` ON `products`.`product_id` = `order_items`.`product_id`
GROUP BY `categories`.`category_id`
ORDER BY `total_revenue` DESC;

/* --Write a SQL query to retrieve the top 5 customers who have made the highest total purchase amount. Display the customer name along with the total purchase amount in descending order of the purchase amount. */
SELECT `customers`.`name`, SUM(`order_items`.`quantity` * `order_items`.`unit_price`) AS `total_purchase_amount`
FROM `customers`
JOIN `orders` ON `customers`.`customer_id` = `orders`.`customer_id`
JOIN `order_items` ON `orders`.`order_id` = `order_items`.`order_id`
GROUP BY `customers`.`customer_id`
ORDER BY `total_purchase_amount` DESC
LIMIT 5